project: 
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600
  
website: 
  title: "Andres Gonzalez"
  site-url: "https://andresgonzalezstats.com/"
  description: "Insights and projects in data analysis, biostatistics, and applied statistics."
  favicon: img/icon.png
  open-graph:
    locale: en_EN
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@AndresAnalytics"
    site: "@AndresAnalytics"
    card-style: summary_large_image
  comments: 
    utterances: 
      repo: OKcomputer626/Andres-Portfolio
      label: "comments"
      theme: github-light
      issue-term: pathname
      
  navbar:
    logo: img/icon.png
    tools:
      - icon: github
        href: https://github.com/OKcomputer626
        aria-label: "GitHub"
    right: 
      - text: About
        aria-label: "About Me"
        href: /about/
      - text: Blog
        aria-label: "Read blog posts"
        href: /blog/
      - text: Visualization
        aria-label: "Data visualization projects"
        href: /visualization/
      - text: Projects
        aria-label: "Project Portfolio"
        href: /project/
      - text: Spotify
        aria-label: "My Spotify"
        href: /spotify/
        
  page-footer: 
    left: >-
      &#169; 2025 Andres Gonzalez &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="/accessibility.html" title="Accessibility commitment" target="_blank" rel="noopener">{{< fa universal-access >}}</a>
      <a class="link-dark me-1" href="https://bsky.app/profile/andresanalytics.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< fa brands bluesky >}}</a>
      <a class="link-dark me-1" href="https://www.linkedin.com/in/andresgonzalez26/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://github.com/OKcomputer626" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      
    right: 
      - text: "Accessibility"
        aria-label: "Accessibility Commitment"
        href: /accessibility/
      - text: "Contact"
        aria-label: "Contact Form"
        href: /contact/
      - text: "License"
        aria-label: "License Details"
        href: /license/

execute:
  freeze: auto

format: 
  html: 
    theme: 
      light: 
        - cosmo
        - assets/andres-theme-light.scss
        - assets/andres/colors-light.scss
        - assets/andres/fonts.scss
      dark: 
        - cosmo
        - assets/andres-theme-dark.scss
        - assets/andres/colors-dark.scss
    highlight-style: 
      light: assets/andres/a11y-light.theme
      dark: assets/andres/a11y-light.theme
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

include-in-header: assets/andres/umami.html
    