authorname: "Andres Gonzalez"
draft: false

project:
  type: website

  preview: 
    port: 3751
    browser: true
    watch-inputs: true
    navigate: true

title-meta: "Andres Gonzalez"
description-meta: "Data Scientist & Statistician | Master's in Applied Statistics | Specializing in Bayesian Methods, Sports Analytics, and Crime Analytics"

website:
  title: "Andres Gonzalez"
  site-url: https://andresgonzalezstats.com/
  image: img/Andres_Gonzalez.png
  back-to-top-navigation: true
  
  repo-url: "https://github.com/OKcomputer626/Andres-Portfolio"
  repo-branch: master
  
  search: 
    location: navbar
    type: textbox
  
  navbar:
    pinned: true
    logo: /img/data.png
    left:
      - text: Blog
        href: blog/index.qmd
      - text: Visualization
        href: visualization/index.qmd
      - text: Resume
        href: resume/index.qmd
      - text: Spotify
        href: Spotify/index.qmd
    right:
      - icon: twitter-x
        href: https://twitter.com/AndresAnalytics
      - icon: github
        href: https://github.com/OKcomputer626
      - icon: linkedin
        href: https://linkedin.com/in/andresgonzalez26
      - icon: envelope
        aria-label: email
        href: "mailto:gonzalez.andrespsg@gmail.com"
  
  favicon: img/favicon.ico
  
  twitter-card: 
    creator: "@AndresAnalytics"
    image: "/img/Andres_Gonzalez.png"
    
  open-graph: 
    image: "/img/Andres_Gonzalez.png"
    locale: en_US
    
  google-analytics: "G-MDSNGGTV5L"
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2024 Andres Gonzalez</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span> 
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block"><a href="https://github.com/OKcomputer626/Andres-Portfolio">View the source at {{< fa brands github >}} GitHub</a></span>
  
execute:
  freeze: true
  
filters:
  - html/newpagelink.lua

format:
  html:
    include-in-header: html/seo.html
    fontsize: 1.1em
    theme: 
      - flatly
      - html/styles.scss
    toc: false
    grid: 
      body-width: 900px
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai