authorname: "Andres Gonzalez"

project:
  type: website

  preview: 
    port: 3751
    browser: true
    watch-inputs: true
    navigate: true

title-meta: "Andres Gonzalez"
description-meta: "Data Scientist & Statistician | Master's in Applied Statistics | Specializing in Bayesian Methods, Sports Analytics, and Crime Analytics"

website:
  title: "Andres Gonzalez"
  description: "Data Scientist & Statistician | Master's in Applied Statistics | Specializing in Bayesian Methods, Sports Analytics, and Crime Analytics"
  site-url: https://andresgonzalezstats.com/
  image: img/Andres_Gonzalez.png
  back-to-top-navigation: true
  
  repo-url: "https://github.com/OKcomputer626/Andres-Portfolio"
  repo-branch: master
